[colors.primary]
background = '#0f1416'
foreground = '#dee3e6'

[colors.selection]
text = '#dee3e6'
background = '#004e5e'

[colors.cursor]
text = '#0f1416'
cursor = '#86d1e9'

[colors.normal]
black   = '#0f1416'
red     = '#e64c4d'
green   = '#75d66e'
yellow  = '#dbcd7b'
blue    = '#3f91ab'
magenta = '#73a0ae'
cyan    = '#86d1e9'
white   = '#abb2bf'

[colors.bright]
black   = '#5c6370'
red     = '#e05f64'
green   = '#8be086'
yellow  = '#e8dc97'
blue    = '#8fe0fa'
magenta = '#37868b'
cyan    = '#567e96'
white   = '#ffffff'
